name: imagebutton
version: 0.0.4
authors:
  - Mario Chamuty <chamuty@versiontwo.sk>
  - Christian Danizek <danizek@versiontwo.sk>
description: >
  ImageButton is simple plugin that allows you to use your images as simple buttons with two different faces (pressed / unpressed).
homepage: https://github.com/version-two/flutter_imagebutton

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: sk.v2.packages.imagebutton
    pluginClass: ImagebuttonPluginc